-- TERRIA data model, based on the Supabase schema specification authored by Nano.
-- This migration intentionally creates domain schemas instead of adding tables to public.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists postgis with schema extensions;

create schema if not exists core;
create schema if not exists satellite;
create schema if not exists climate;
create schema if not exists agro;
create schema if not exists timelapse;
create schema if not exists cert;
create schema if not exists ops;

create function core.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table core.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

create table core.fields (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete restrict,
  name text not null check (char_length(name) between 1 and 120),
  description text check (char_length(description) <= 2000),
  boundary extensions.geography(MULTIPOLYGON, 4326) not null,
  centroid extensions.geography(POINT, 4326),
  area_hectares numeric(12, 2) not null check (area_hectares > 0),
  country char(2) not null default 'AR',
  province text,
  locality text,
  visibility text not null default 'private'
    check (visibility in ('private', 'public')),
  public_slug text unique,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((visibility = 'private' and public_slug is null) or visibility = 'public')
);

create index fields_owner_ix on core.fields (owner_id) where archived_at is null;
create index fields_boundary_gix on core.fields using gist (boundary);
create unique index fields_public_slug_ix on core.fields (public_slug)
  where public_slug is not null and archived_at is null;

create trigger fields_set_updated_at
before update on core.fields
for each row execute function core.set_updated_at();

create table core.audit_log (
  id bigint generated always as identity primary key,
  field_id uuid references core.fields(id) on delete set null,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);
create index audit_log_field_occurred_ix on core.audit_log (field_id, occurred_at desc);

create table satellite.sources (
  id smallint generated by default as identity primary key,
  code text unique not null,
  name text not null,
  provider text,
  kind text,
  license text
);

create table satellite.observations (
  id bigint generated always as identity primary key,
  field_id uuid not null references core.fields(id) on delete cascade,
  source_id smallint not null references satellite.sources(id),
  month date not null check (month = date_trunc('month', month)::date),
  index_code text not null,
  stat text not null check (stat in ('median', 'max', 'mean')),
  value numeric(6, 4) not null,
  dataset_version text not null,
  processing_version text not null,
  created_at timestamptz not null default now(),
  unique (field_id, source_id, month, index_code, stat, processing_version)
);
create index observations_field_month_ix on satellite.observations (field_id, month);

create table climate.monthly (
  id bigint generated always as identity primary key,
  field_id uuid not null references core.fields(id) on delete cascade,
  source_id smallint not null references satellite.sources(id),
  month date not null check (month = date_trunc('month', month)::date),
  precip_mm numeric(8, 2),
  temp_mean_c numeric(5, 2),
  temp_min_c numeric(5, 2),
  temp_max_c numeric(5, 2),
  et0_mm numeric(8, 2),
  gdd numeric(8, 2),
  processing_version text not null,
  created_at timestamptz not null default now(),
  unique (field_id, source_id, month, processing_version)
);
create index climate_monthly_field_month_ix on climate.monthly (field_id, month);

create table agro.campaigns (
  id uuid primary key default gen_random_uuid(),
  field_id uuid not null references core.fields(id) on delete cascade,
  season_label text not null,
  start_date date,
  end_date date,
  crop_code text,
  crop_confidence numeric(4, 3) check (crop_confidence between 0 and 1),
  detection_source text,
  status text not null default 'detected'
    check (status in ('detected', 'confirmed', 'corrected', 'rejected')),
  created_at timestamptz not null default now(),
  check (end_date is null or start_date is null or end_date >= start_date),
  unique (field_id, season_label)
);

create table agro.events (
  id uuid primary key default gen_random_uuid(),
  field_id uuid not null references core.fields(id) on delete cascade,
  campaign_id uuid references agro.campaigns(id) on delete set null,
  event_type text not null,
  occurred_on date,
  source text,
  confidence numeric(4, 3) check (confidence between 0 and 1),
  verification_status text not null default 'unverified'
    check (verification_status in ('unverified', 'confirmed', 'rejected', 'corrected')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index events_field_occurred_ix on agro.events (field_id, occurred_on);

create table agro.soil (
  id uuid primary key default gen_random_uuid(),
  field_id uuid not null references core.fields(id) on delete cascade,
  depth_cm integer,
  clay_pct numeric(5, 2),
  sand_pct numeric(5, 2),
  silt_pct numeric(5, 2),
  ph numeric(4, 2),
  organic_carbon numeric(6, 2),
  source_id smallint references satellite.sources(id),
  retrieved_at date,
  unique nulls not distinct (field_id, depth_cm, source_id)
);

create table core.documents (
  id uuid primary key default gen_random_uuid(),
  field_id uuid not null references core.fields(id) on delete cascade,
  campaign_id uuid references agro.campaigns(id) on delete set null,
  kind text not null,
  storage_ref text not null,
  sha256 text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  mime text,
  byte_size bigint check (byte_size is null or byte_size >= 0),
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index documents_field_ix on core.documents (field_id);

create table timelapse.datasets (
  id uuid primary key default gen_random_uuid(),
  field_id uuid not null references core.fields(id) on delete cascade,
  requested_by uuid references auth.users(id) on delete set null,
  source_mode text not null check (source_mode in ('synthetic', 'real')),
  is_demo boolean not null default false,
  date_from date,
  date_to date,
  status text not null default 'queued'
    check (status in ('queued', 'running', 'partial', 'completed', 'failed')),
  request_hash text not null,
  manifest jsonb,
  is_public boolean not null default false,
  public_slug text unique,
  created_at timestamptz not null default now(),
  check (date_to is null or date_from is null or date_to >= date_from),
  unique (field_id, request_hash)
);
create index datasets_field_ix on timelapse.datasets (field_id, created_at desc);

create table timelapse.frames (
  id bigint generated always as identity primary key,
  dataset_id uuid not null references timelapse.datasets(id) on delete cascade,
  frame_date date not null,
  weather jsonb,
  satellite jsonb,
  created_at timestamptz not null default now(),
  unique (dataset_id, frame_date)
);

create table timelapse.assets (
  id bigint generated always as identity primary key,
  frame_id bigint not null references timelapse.frames(id) on delete cascade,
  layer text not null check (layer in ('rgb', 'ndvi')),
  storage_ref text not null,
  mime text,
  byte_size bigint check (byte_size is null or byte_size >= 0),
  unique (frame_id, layer)
);

create table timelapse.publications (
  id uuid primary key default gen_random_uuid(),
  dataset_id uuid not null references timelapse.datasets(id) on delete cascade,
  public_slug text unique not null,
  published_at timestamptz not null default now(),
  unpublished_at timestamptz,
  check (unpublished_at is null or unpublished_at >= published_at)
);

create table cert.certifications (
  id uuid primary key default gen_random_uuid(),
  field_id uuid not null references core.fields(id) on delete restrict,
  version integer not null check (version > 0),
  schema_version text not null,
  algorithm_version text not null,
  cert_uid text unique not null,
  period_from integer not null,
  period_to integer not null,
  status text not null default 'draft'
    check (status in ('draft', 'pending_anchor', 'anchored', 'failed', 'superseded')),
  content_hash text check (content_hash is null or content_hash ~ '^[0-9a-f]{64}$'),
  prev_content_hash text check (prev_content_hash is null or prev_content_hash ~ '^[0-9a-f]{64}$'),
  issued_at timestamptz,
  created_at timestamptz not null default now(),
  check (period_to >= period_from),
  unique (field_id, version)
);

create table cert.inputs (
  certification_id uuid not null references cert.certifications(id) on delete cascade,
  kind text not null,
  ref_id text not null,
  row_hash text not null check (row_hash ~ '^[0-9a-f]{64}$'),
  frozen_row jsonb not null,
  primary key (certification_id, kind, ref_id)
);

create table cert.payloads (
  certification_id uuid primary key references cert.certifications(id) on delete cascade,
  storage_ref text not null,
  byte_size integer not null check (byte_size >= 0),
  content_hash text not null check (content_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now()
);

create table cert.anchors (
  id uuid primary key default gen_random_uuid(),
  certification_id uuid unique not null references cert.certifications(id) on delete cascade,
  provider text not null default 'solana',
  cluster text not null default 'devnet',
  memo_payload text not null,
  tx_signature text unique,
  slot bigint,
  block_time timestamptz,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  error text,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz
);

create table ops.jobs (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('enrichment', 'timelapse', 'anchor')),
  ref_id uuid not null,
  state text not null default 'queued' check (state in ('queued', 'running', 'done', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  lease_until timestamptz,
  last_error text,
  not_before timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index jobs_ready_ix on ops.jobs (not_before, created_at)
  where state = 'queued';
create trigger jobs_set_updated_at
before update on ops.jobs
for each row execute function core.set_updated_at();

-- RLS applies even though the Python API is the normal data access path.
alter table core.profiles enable row level security;
alter table core.fields enable row level security;
alter table core.documents enable row level security;
alter table core.audit_log enable row level security;
alter table satellite.sources enable row level security;
alter table satellite.observations enable row level security;
alter table climate.monthly enable row level security;
alter table agro.campaigns enable row level security;
alter table agro.events enable row level security;
alter table agro.soil enable row level security;
alter table timelapse.datasets enable row level security;
alter table timelapse.frames enable row level security;
alter table timelapse.assets enable row level security;
alter table timelapse.publications enable row level security;
alter table cert.certifications enable row level security;
alter table cert.inputs enable row level security;
alter table cert.payloads enable row level security;
alter table cert.anchors enable row level security;
alter table ops.jobs enable row level security;

create policy "profiles are visible to their owner" on core.profiles
for select to authenticated using ((select auth.uid()) = id);
create policy "profiles are updated by their owner" on core.profiles
for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "owners manage their fields" on core.fields
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "owners read field documents" on core.documents
for select to authenticated using (
  exists (select 1 from core.fields f where f.id = field_id and f.owner_id = (select auth.uid()))
);
create policy "owners read field audit" on core.audit_log
for select to authenticated using (
  exists (select 1 from core.fields f where f.id = field_id and f.owner_id = (select auth.uid()))
);
create policy "authenticated users read source catalog" on satellite.sources
for select to authenticated using (true);

-- Derived data stays read-only to owners. Workers use server-only credentials.
create policy "owners read observations" on satellite.observations
for select to authenticated using (exists (select 1 from core.fields f where f.id = field_id and f.owner_id = (select auth.uid())));
create policy "owners read climate" on climate.monthly
for select to authenticated using (exists (select 1 from core.fields f where f.id = field_id and f.owner_id = (select auth.uid())));
create policy "owners read campaigns" on agro.campaigns
for select to authenticated using (exists (select 1 from core.fields f where f.id = field_id and f.owner_id = (select auth.uid())));
create policy "owners read events" on agro.events
for select to authenticated using (exists (select 1 from core.fields f where f.id = field_id and f.owner_id = (select auth.uid())));
create policy "owners read soil" on agro.soil
for select to authenticated using (exists (select 1 from core.fields f where f.id = field_id and f.owner_id = (select auth.uid())));
create policy "owners read timelapse datasets" on timelapse.datasets
for select to authenticated using (exists (select 1 from core.fields f where f.id = field_id and f.owner_id = (select auth.uid())));
create policy "owners read certifications" on cert.certifications
for select to authenticated using (exists (select 1 from core.fields f where f.id = field_id and f.owner_id = (select auth.uid())));
